apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  template:
    spec:
      containers:
        - name: guestbook
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 3
            periodSeconds: 4
            failureThreshold: 2
